"""first migrations

Revision ID: 13f813bbe11c
Revises: 
Create Date: 2020-10-24 16:58:54.315190

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '13f813bbe11c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organization',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fullname', sa.String(length=128), nullable=True),
    sa.Column('name', sa.String(length=32), nullable=True),
    sa.Column('inn', sa.String(length=12), nullable=True),
    sa.Column('kpp', sa.String(length=9), nullable=True),
    sa.Column('okpo', sa.String(length=10), nullable=True),
    sa.Column('off_address', sa.String(), nullable=True),
    sa.Column('post_address', sa.String(), nullable=True),
    sa.Column('head_position', sa.String(length=30), nullable=True),
    sa.Column('last_name', sa.String(length=32), nullable=True),
    sa.Column('first_name', sa.String(length=32), nullable=True),
    sa.Column('patronymic', sa.String(length=32), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('accounting', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_organization_accounting'), 'organization', ['accounting'], unique=False)
    op.create_index(op.f('ix_organization_email'), 'organization', ['email'], unique=True)
    op.create_index(op.f('ix_organization_first_name'), 'organization', ['first_name'], unique=False)
    op.create_index(op.f('ix_organization_fullname'), 'organization', ['fullname'], unique=True)
    op.create_index(op.f('ix_organization_inn'), 'organization', ['inn'], unique=True)
    op.create_index(op.f('ix_organization_last_name'), 'organization', ['last_name'], unique=False)
    op.create_index(op.f('ix_organization_name'), 'organization', ['name'], unique=False)
    op.create_index(op.f('ix_organization_off_address'), 'organization', ['off_address'], unique=False)
    op.create_index(op.f('ix_organization_patronymic'), 'organization', ['patronymic'], unique=False)
    op.create_index(op.f('ix_organization_post_address'), 'organization', ['post_address'], unique=False)
    op.create_table('role',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_role_name'), 'role', ['name'], unique=True)
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('divisions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('abbreviation', sa.String(length=8), nullable=True),
    sa.Column('organization_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_divisions_abbreviation'), 'divisions', ['abbreviation'], unique=False)
    op.create_index(op.f('ix_divisions_email'), 'divisions', ['email'], unique=True)
    op.create_index(op.f('ix_divisions_name'), 'divisions', ['name'], unique=True)
    op.create_table('staff',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('last_name', sa.String(length=32), nullable=True),
    sa.Column('first_name', sa.String(length=32), nullable=True),
    sa.Column('patronymic', sa.String(length=32), nullable=True),
    sa.Column('division_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.Column('organization_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['division_id'], ['divisions.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_staff_first_name'), 'staff', ['first_name'], unique=False)
    op.create_index(op.f('ix_staff_last_name'), 'staff', ['last_name'], unique=False)
    op.create_index(op.f('ix_staff_patronymic'), 'staff', ['patronymic'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_staff_patronymic'), table_name='staff')
    op.drop_index(op.f('ix_staff_last_name'), table_name='staff')
    op.drop_index(op.f('ix_staff_first_name'), table_name='staff')
    op.drop_table('staff')
    op.drop_index(op.f('ix_divisions_name'), table_name='divisions')
    op.drop_index(op.f('ix_divisions_email'), table_name='divisions')
    op.drop_index(op.f('ix_divisions_abbreviation'), table_name='divisions')
    op.drop_table('divisions')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_role_name'), table_name='role')
    op.drop_table('role')
    op.drop_index(op.f('ix_organization_post_address'), table_name='organization')
    op.drop_index(op.f('ix_organization_patronymic'), table_name='organization')
    op.drop_index(op.f('ix_organization_off_address'), table_name='organization')
    op.drop_index(op.f('ix_organization_name'), table_name='organization')
    op.drop_index(op.f('ix_organization_last_name'), table_name='organization')
    op.drop_index(op.f('ix_organization_inn'), table_name='organization')
    op.drop_index(op.f('ix_organization_fullname'), table_name='organization')
    op.drop_index(op.f('ix_organization_first_name'), table_name='organization')
    op.drop_index(op.f('ix_organization_email'), table_name='organization')
    op.drop_index(op.f('ix_organization_accounting'), table_name='organization')
    op.drop_table('organization')
    # ### end Alembic commands ###
