"""empty message

Revision ID: b80f709b49e6
Revises: d7d0a1a4701e
Create Date: 2021-07-16 22:02:40.829056

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b80f709b49e6'
down_revision = 'd7d0a1a4701e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('unitrates', sa.Column('end_date', sa.Date(), nullable=True))
    op.add_column('unitrates', sa.Column('start_date', sa.Date(), nullable=True))
    op.create_index(op.f('ix_unitrates_end_date'), 'unitrates', ['end_date'], unique=False)
    op.create_index(op.f('ix_unitrates_start_date'), 'unitrates', ['start_date'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_unitrates_start_date'), table_name='unitrates')
    op.drop_index(op.f('ix_unitrates_end_date'), table_name='unitrates')
    op.drop_column('unitrates', 'start_date')
    op.drop_column('unitrates', 'end_date')
    # ### end Alembic commands ###
