"""empty message

Revision ID: d7d0a1a4701e
Revises: 13f813bbe11c
Create Date: 2021-01-30 23:00:26.251038

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd7d0a1a4701e'
down_revision = '13f813bbe11c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('typecontract',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('typename', sa.String(length=64), nullable=True),
    sa.Column('we_sell', sa.Boolean(), nullable=True),
    sa.Column('protected', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_typecontract_typename'), 'typecontract', ['typename'], unique=True)
    op.create_index(op.f('ix_typecontract_we_sell'), 'typecontract', ['we_sell'], unique=False)
    op.create_table('typefulfillment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('typename', sa.String(length=64), nullable=True),
    sa.Column('protected', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_typefulfillment_typename'), 'typefulfillment', ['typename'], unique=True)
    op.create_table('typemachinery',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('typename', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_typemachinery_typename'), 'typemachinery', ['typename'], unique=True)
    op.create_table('typesownership',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=True),
    sa.Column('protected', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_typesownership_name'), 'typesownership', ['name'], unique=True)
    op.create_table('units',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=16), nullable=True),
    sa.Column('full_name', sa.String(length=128), nullable=True),
    sa.Column('OKEI', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_units_OKEI'), 'units', ['OKEI'], unique=False)
    op.create_index(op.f('ix_units_full_name'), 'units', ['full_name'], unique=False)
    op.create_index(op.f('ix_units_name'), 'units', ['name'], unique=False)
    op.create_table('contract',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type_id', sa.Integer(), nullable=True),
    sa.Column('typefulfillment_id', sa.Integer(), nullable=True),
    sa.Column('accounting_method', sa.Integer(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('organization', sa.Integer(), nullable=True),
    sa.Column('contractor', sa.Integer(), nullable=True),
    sa.Column('number', sa.String(length=32), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('full_name', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['contractor'], ['organization.id'], ),
    sa.ForeignKeyConstraint(['organization'], ['organization.id'], ),
    sa.ForeignKeyConstraint(['type_id'], ['typecontract.id'], ),
    sa.ForeignKeyConstraint(['typefulfillment_id'], ['typefulfillment.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contract_date'), 'contract', ['date'], unique=False)
    op.create_index(op.f('ix_contract_full_name'), 'contract', ['full_name'], unique=False)
    op.create_index(op.f('ix_contract_name'), 'contract', ['name'], unique=False)
    op.create_index(op.f('ix_contract_number'), 'contract', ['number'], unique=False)
    op.create_index(op.f('ix_contract_price'), 'contract', ['price'], unique=False)
    op.create_table('materials',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('unit', sa.Integer(), nullable=True),
    sa.Column('full_name', sa.String(length=128), nullable=True),
    sa.ForeignKeyConstraint(['unit'], ['units.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_materials_full_name'), 'materials', ['full_name'], unique=False)
    op.create_index(op.f('ix_materials_unit'), 'materials', ['unit'], unique=False)
    op.create_table('modelsmachinery',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('type_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['type_id'], ['typemachinery.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_modelsmachinery_name'), 'modelsmachinery', ['name'], unique=True)
    op.create_table('roads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('abbreviation', sa.String(length=16), nullable=True),
    sa.Column('length', sa.Integer(), nullable=True),
    sa.Column('start_address', sa.Integer(), nullable=True),
    sa.Column('type_of_ownership', sa.Integer(), nullable=True),
    sa.Column('owner', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['owner'], ['organization.id'], ),
    sa.ForeignKeyConstraint(['type_of_ownership'], ['typesownership.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_roads_abbreviation'), 'roads', ['abbreviation'], unique=False)
    op.create_index(op.f('ix_roads_name'), 'roads', ['name'], unique=False)
    op.create_table('divisionscontract',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('division', sa.Integer(), nullable=True),
    sa.Column('contract', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['contract'], ['contract.id'], ),
    sa.ForeignKeyConstraint(['division'], ['divisions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('heaps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=16), nullable=True),
    sa.Column('road', sa.Integer(), nullable=True),
    sa.Column('address', sa.Integer(), nullable=True),
    sa.Column('distance_from_road', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['road'], ['roads.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_heaps_address'), 'heaps', ['address'], unique=False)
    op.create_index(op.f('ix_heaps_name'), 'heaps', ['name'], unique=False)
    op.create_index(op.f('ix_heaps_road'), 'heaps', ['road'], unique=False)
    op.create_table('planeprice',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('model', sa.Integer(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['model'], ['modelsmachinery.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_planeprice_end_date'), 'planeprice', ['end_date'], unique=False)
    op.create_index(op.f('ix_planeprice_start_date'), 'planeprice', ['start_date'], unique=False)
    op.create_table('roadsincontract',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contract', sa.Integer(), nullable=True),
    sa.Column('road', sa.Integer(), nullable=True),
    sa.Column('start_address', sa.Integer(), nullable=True),
    sa.Column('end_address', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['contract'], ['contract.id'], ),
    sa.ForeignKeyConstraint(['road'], ['roads.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_roadsincontract_end_address'), 'roadsincontract', ['end_address'], unique=False)
    op.create_index(op.f('ix_roadsincontract_start_address'), 'roadsincontract', ['start_address'], unique=False)
    op.create_table('roadstructure',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.SmallInteger(), nullable=True),
    sa.Column('road', sa.Integer(), nullable=True),
    sa.Column('address', sa.Integer(), nullable=True),
    sa.Column('barrier', sa.String(length=32), nullable=True),
    sa.Column('length', sa.Integer(), nullable=True),
    sa.Column('roadway_area', sa.Integer(), nullable=True),
    sa.Column('sidewalk_area', sa.Integer(), nullable=True),
    sa.Column('material', sa.Integer(), nullable=True),
    sa.Column('diameter', sa.Integer(), nullable=True),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('lifting_capacity', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['material'], ['materials.id'], ),
    sa.ForeignKeyConstraint(['road'], ['roads.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_roadstructure_address'), 'roadstructure', ['address'], unique=False)
    op.create_index(op.f('ix_roadstructure_barrier'), 'roadstructure', ['barrier'], unique=False)
    op.create_index(op.f('ix_roadstructure_lifting_capacity'), 'roadstructure', ['lifting_capacity'], unique=False)
    op.create_index(op.f('ix_roadstructure_material'), 'roadstructure', ['material'], unique=False)
    op.create_index(op.f('ix_roadstructure_type'), 'roadstructure', ['type'], unique=False)
    op.create_table('unitrates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contract', sa.Integer(), nullable=True),
    sa.Column('job_title', sa.String(length=256), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('zone', sa.SmallInteger(), nullable=True),
    sa.Column('season_winter', sa.Boolean(), nullable=True),
    sa.Column('tag', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['contract'], ['contract.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_unitrates_job_title'), 'unitrates', ['job_title'], unique=False)
    op.create_index(op.f('ix_unitrates_season_winter'), 'unitrates', ['season_winter'], unique=False)
    op.create_index(op.f('ix_unitrates_tag'), 'unitrates', ['tag'], unique=False)
    op.create_index(op.f('ix_unitrates_zone'), 'unitrates', ['zone'], unique=False)
    op.create_table('machinery',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('model_id', sa.Integer(), nullable=True),
    sa.Column('type_id', sa.Integer(), nullable=True),
    sa.Column('division', sa.Integer(), nullable=True),
    sa.Column('driver_id', sa.Integer(), nullable=True),
    sa.Column('number', sa.String(length=15), nullable=True),
    sa.ForeignKeyConstraint(['division'], ['divisions.id'], ),
    sa.ForeignKeyConstraint(['driver_id'], ['staff.id'], ),
    sa.ForeignKeyConstraint(['model_id'], ['modelsmachinery.id'], ),
    sa.ForeignKeyConstraint(['type_id'], ['typemachinery.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_machinery_division'), 'machinery', ['division'], unique=False)
    op.create_index(op.f('ix_machinery_driver_id'), 'machinery', ['driver_id'], unique=False)
    op.create_index(op.f('ix_machinery_model_id'), 'machinery', ['model_id'], unique=False)
    op.create_index(op.f('ix_machinery_name'), 'machinery', ['name'], unique=True)
    op.create_index(op.f('ix_machinery_number'), 'machinery', ['number'], unique=True)
    op.create_index(op.f('ix_machinery_type_id'), 'machinery', ['type_id'], unique=False)
    op.create_table('work',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contract_id', sa.Integer(), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('unit_rate_id', sa.Integer(), nullable=True),
    sa.Column('road_id', sa.Integer(), nullable=True),
    sa.Column('address', sa.Integer(), nullable=True),
    sa.Column('address2', sa.Integer(), nullable=True),
    sa.Column('volume', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['contract_id'], ['contract.id'], ),
    sa.ForeignKeyConstraint(['road_id'], ['roads.id'], ),
    sa.ForeignKeyConstraint(['unit_rate_id'], ['unitrates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_work_contract_id'), 'work', ['contract_id'], unique=False)
    op.create_index(op.f('ix_work_date'), 'work', ['date'], unique=False)
    op.create_index(op.f('ix_work_road_id'), 'work', ['road_id'], unique=False)
    op.create_index(op.f('ix_work_unit_rate_id'), 'work', ['unit_rate_id'], unique=False)
    op.create_table('usedmashines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('work_id', sa.Integer(), nullable=True),
    sa.Column('mashinery_id', sa.Integer(), nullable=True),
    sa.Column('driver_id', sa.Integer(), nullable=True),
    sa.Column('volume', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['driver_id'], ['staff.id'], ),
    sa.ForeignKeyConstraint(['mashinery_id'], ['machinery.id'], ),
    sa.ForeignKeyConstraint(['work_id'], ['work.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usedmashines_driver_id'), 'usedmashines', ['driver_id'], unique=False)
    op.create_index(op.f('ix_usedmashines_mashinery_id'), 'usedmashines', ['mashinery_id'], unique=False)
    op.create_index(op.f('ix_usedmashines_work_id'), 'usedmashines', ['work_id'], unique=False)
    op.create_table('usedmaterials',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('work_id', sa.Integer(), nullable=True),
    sa.Column('material', sa.Integer(), nullable=True),
    sa.Column('source', sa.Integer(), nullable=True),
    sa.Column('volume', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['material'], ['materials.id'], ),
    sa.ForeignKeyConstraint(['source'], ['heaps.id'], ),
    sa.ForeignKeyConstraint(['work_id'], ['work.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usedmaterials_material'), 'usedmaterials', ['material'], unique=False)
    op.create_index(op.f('ix_usedmaterials_source'), 'usedmaterials', ['source'], unique=False)
    op.create_index(op.f('ix_usedmaterials_work_id'), 'usedmaterials', ['work_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_usedmaterials_work_id'), table_name='usedmaterials')
    op.drop_index(op.f('ix_usedmaterials_source'), table_name='usedmaterials')
    op.drop_index(op.f('ix_usedmaterials_material'), table_name='usedmaterials')
    op.drop_table('usedmaterials')
    op.drop_index(op.f('ix_usedmashines_work_id'), table_name='usedmashines')
    op.drop_index(op.f('ix_usedmashines_mashinery_id'), table_name='usedmashines')
    op.drop_index(op.f('ix_usedmashines_driver_id'), table_name='usedmashines')
    op.drop_table('usedmashines')
    op.drop_index(op.f('ix_work_unit_rate_id'), table_name='work')
    op.drop_index(op.f('ix_work_road_id'), table_name='work')
    op.drop_index(op.f('ix_work_date'), table_name='work')
    op.drop_index(op.f('ix_work_contract_id'), table_name='work')
    op.drop_table('work')
    op.drop_index(op.f('ix_machinery_type_id'), table_name='machinery')
    op.drop_index(op.f('ix_machinery_number'), table_name='machinery')
    op.drop_index(op.f('ix_machinery_name'), table_name='machinery')
    op.drop_index(op.f('ix_machinery_model_id'), table_name='machinery')
    op.drop_index(op.f('ix_machinery_driver_id'), table_name='machinery')
    op.drop_index(op.f('ix_machinery_division'), table_name='machinery')
    op.drop_table('machinery')
    op.drop_index(op.f('ix_unitrates_zone'), table_name='unitrates')
    op.drop_index(op.f('ix_unitrates_tag'), table_name='unitrates')
    op.drop_index(op.f('ix_unitrates_season_winter'), table_name='unitrates')
    op.drop_index(op.f('ix_unitrates_job_title'), table_name='unitrates')
    op.drop_table('unitrates')
    op.drop_index(op.f('ix_roadstructure_type'), table_name='roadstructure')
    op.drop_index(op.f('ix_roadstructure_material'), table_name='roadstructure')
    op.drop_index(op.f('ix_roadstructure_lifting_capacity'), table_name='roadstructure')
    op.drop_index(op.f('ix_roadstructure_barrier'), table_name='roadstructure')
    op.drop_index(op.f('ix_roadstructure_address'), table_name='roadstructure')
    op.drop_table('roadstructure')
    op.drop_index(op.f('ix_roadsincontract_start_address'), table_name='roadsincontract')
    op.drop_index(op.f('ix_roadsincontract_end_address'), table_name='roadsincontract')
    op.drop_table('roadsincontract')
    op.drop_index(op.f('ix_planeprice_start_date'), table_name='planeprice')
    op.drop_index(op.f('ix_planeprice_end_date'), table_name='planeprice')
    op.drop_table('planeprice')
    op.drop_index(op.f('ix_heaps_road'), table_name='heaps')
    op.drop_index(op.f('ix_heaps_name'), table_name='heaps')
    op.drop_index(op.f('ix_heaps_address'), table_name='heaps')
    op.drop_table('heaps')
    op.drop_table('divisionscontract')
    op.drop_index(op.f('ix_roads_name'), table_name='roads')
    op.drop_index(op.f('ix_roads_abbreviation'), table_name='roads')
    op.drop_table('roads')
    op.drop_index(op.f('ix_modelsmachinery_name'), table_name='modelsmachinery')
    op.drop_table('modelsmachinery')
    op.drop_index(op.f('ix_materials_unit'), table_name='materials')
    op.drop_index(op.f('ix_materials_full_name'), table_name='materials')
    op.drop_table('materials')
    op.drop_index(op.f('ix_contract_price'), table_name='contract')
    op.drop_index(op.f('ix_contract_number'), table_name='contract')
    op.drop_index(op.f('ix_contract_name'), table_name='contract')
    op.drop_index(op.f('ix_contract_full_name'), table_name='contract')
    op.drop_index(op.f('ix_contract_date'), table_name='contract')
    op.drop_table('contract')
    op.drop_index(op.f('ix_units_name'), table_name='units')
    op.drop_index(op.f('ix_units_full_name'), table_name='units')
    op.drop_index(op.f('ix_units_OKEI'), table_name='units')
    op.drop_table('units')
    op.drop_index(op.f('ix_typesownership_name'), table_name='typesownership')
    op.drop_table('typesownership')
    op.drop_index(op.f('ix_typemachinery_typename'), table_name='typemachinery')
    op.drop_table('typemachinery')
    op.drop_index(op.f('ix_typefulfillment_typename'), table_name='typefulfillment')
    op.drop_table('typefulfillment')
    op.drop_index(op.f('ix_typecontract_we_sell'), table_name='typecontract')
    op.drop_index(op.f('ix_typecontract_typename'), table_name='typecontract')
    op.drop_table('typecontract')
    # ### end Alembic commands ###
